services:
  signer:
    build: .
    container_name: signer-micro
    env_file:
      - ./.env
    volumes:
      - ./signature.p12:/certificates/signature.p12:ro
    restart: always
    networks:
      - shared-network

networks:
  shared-network:
    external: true